# Generated by Django 5.1 on 2026-09-04 16:36

from django.db import migrations

CHORES = [
    ("Take out trash", 1),
    ("Vacuum", 7),
    ("Clean bathroom", 7),
    ("Deep clean kitchen", 14),
]


def seed_chores(apps, schema_editor):
    Chore = apps.get_model("chores", "Chore")
    for name, frequency_days in CHORES:
        Chore.objects.get_or_create(name=name, defaults={"frequency_days": frequency_days})


def unseed_chores(apps, schema_editor):
    Chore = apps.get_model("chores", "Chore")
    Chore.objects.filter(name__in=[name for name, _ in CHORES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_chores, reverse_code=unseed_chores),
    ]
