# Generated by Django 5.2 on 2026-09-05 17:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_seed_predefined_chores'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roommate',
            constraint=models.UniqueConstraint(models.F('household'), django.db.models.functions.text.Lower('name'), name='unique_roommate_name_per_household_ci'),
        ),
    ]
